#!/bin/bash

echo "=========================================="
echo "Vercel 도메인 설정 체크리스트"
echo "=========================================="
echo ""

echo "✅ 1. Vercel 대시보드 설정 확인"
echo "   → https://vercel.com/paulslife2017-hue/ss/settings/domains"
echo ""
echo "   반드시 확인할 사항:"
echo "   ✓ 'seoulzen.com' (non-www)가 Primary Domain인지 확인"
echo "   ✓ 'www.seoulzen.com'가 'seoulzen.com'으로 리다이렉트 설정되어 있는지 확인"
echo "   ✓ Redirect to: seoulzen.com (Permanent 301)"
echo ""

echo "✅ 2. DNS 설정 확인 (Cloudflare/도메인 제공업체)"
echo "   → DNS 레코드가 다음과 같아야 합니다:"
echo ""
echo "   A 레코드:"
echo "   Name: @              → 76.76.21.21"
echo "   Name: www            → 76.76.21.98 (또는 CNAME: cname.vercel-dns.com)"
echo ""
echo "   또는"
echo ""
echo "   CNAME 레코드:"
echo "   Name: @              → cname.vercel-dns.com"
echo "   Name: www            → cname.vercel-dns.com"
echo ""

echo "✅ 3. Google Search Console 속성 설정"
echo "   → https://search.google.com/search-console"
echo ""
echo "   확인 사항:"
echo "   ✓ 'seoulzen.com' (non-www) 속성만 사용"
echo "   ✓ 'www.seoulzen.com' 속성이 있다면 삭제 또는 무시"
echo "   ✓ 선호 도메인: seoulzen.com"
echo ""

echo "✅ 4. sitemap.xml 재제출"
echo "   Google Search Console에서:"
echo "   → Sitemaps → 'https://seoulzen.com/sitemap.xml' 추가"
echo "   → 기존 www 버전 sitemap 제거"
echo ""

echo "✅ 5. 주요 URL 색인 재요청"
echo "   URL 검사 도구 사용:"
echo "   → https://seoulzen.com/"
echo "   → https://seoulzen.com/blog.html"
echo "   → 주요 블로그 글 5-10개"
echo ""

echo "=========================================="
echo "⚠️  가장 중요한 단계"
echo "=========================================="
echo ""
echo "Vercel 대시보드에서 도메인 설정을 확인하고"
echo "www.seoulzen.com → seoulzen.com 리다이렉트가"
echo "올바르게 설정되어 있는지 반드시 확인하세요!"
echo ""
echo "설정 방법:"
echo "1. Vercel 대시보드 → 프로젝트 → Settings → Domains"
echo "2. www.seoulzen.com 클릭"
echo "3. 'Redirect to' 섹션에서 'seoulzen.com' 선택"
echo "4. 'Permanent (301)' 옵션 선택"
echo "5. 저장"
echo ""
echo "=========================================="
