#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  Google 강제 재크롤링 가이드                                   ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "🎯 목표: Google이 301 리다이렉트를 인식하도록 강제 재크롤링"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: 301 리다이렉트 동작 확인"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "명령어 실행 중..."
curl -I https://www.seoulzen.com/ 2>&1 | grep -E "HTTP|location"
echo ""

if curl -I https://www.seoulzen.com/ 2>&1 | grep -q "HTTP/2 301"; then
    echo "✅ 301 리다이렉트 정상 작동 중!"
else
    echo "⚠️  301 리다이렉트가 아직 작동하지 않습니다."
    echo "   Vercel 대시보드 설정을 다시 확인하세요."
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Google Search Console에서 강제 재크롤링"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "👉 Google Search Console 접속:"
echo "   https://search.google.com/search-console"
echo ""
echo "1️⃣  www 버전 테스트 (301 감지 확인)"
echo "   ────────────────────────────────────────"
echo "   a) URL 검사 도구 클릭"
echo "   b) 입력: https://www.seoulzen.com/"
echo "   c) '실제 URL 테스트' 클릭"
echo "   d) 결과 확인: '301 리다이렉트' 표시되는지 확인"
echo ""
echo "2️⃣  non-www 버전 색인 요청 (표준 URL)"
echo "   ────────────────────────────────────────"
echo "   a) URL 검사 도구에서"
echo "   b) 입력: https://seoulzen.com/"
echo "   c) '색인 생성 요청' 클릭"
echo "   d) 대기: 1-3일"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: 주요 페이지 5-10개 색인 요청"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "다음 URL들을 URL 검사 도구에서 '색인 생성 요청':"
echo ""
echo "✓ https://seoulzen.com/"
echo "✓ https://seoulzen.com/blog.html"
echo "✓ https://seoulzen.com/blog/gangnam-massage-guide-2025.html"
echo "✓ https://seoulzen.com/blog/korean-skincare-routine-beginners-2025.html"
echo "✓ https://seoulzen.com/blog/gangnam-head-spa-complete-guide-2025.html"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: 기다리기 (중요!)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏰ Google이 변경사항을 인식하는 시간:"
echo "   - 즉시 재크롤링: 1-3일"
echo "   - 색인 업데이트: 3-7일"
echo "   - '중복 페이지' 오류 해결: 1-2주"
echo ""
echo "💡 팁:"
echo "   - 매일 1-2개씩 추가로 색인 요청 (한 번에 너무 많이 하지 말 것)"
echo "   - 1주일 후 Google Search Console에서 진행상황 확인"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 체크리스트"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "□ 301 리다이렉트 작동 확인 (위에서 확인됨)"
echo "□ www 버전 '실제 URL 테스트' 완료"
echo "□ non-www 버전 '색인 생성 요청' 완료"
echo "□ 주요 페이지 5-10개 색인 요청 완료"
echo "□ 1주일 후 진행상황 체크 예약"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
